rm -rf D0spectra_Note.aux
rm -rf D0spectra_Note.bbl
rm -rf D0spectra_Note.blg
rm -rf D0spectra_Note.fdb_latexmk
rm -rf D0spectra_Note.fls
rm -rf D0spectra_Note.log
rm -rf D0spectra_Note.out
rm -rf D0spectra_Note.synctex.gz
rm -rf D0spectra_Note.synctex.gz\(busy\)
rm -rf D0spectra_Note.toc
rm -rf D0spectra_Note.log
rm -rf introduction.log
rm -rf dataSets.log
rm -rf D0Reconstruct.log
rm -rf efficiency.log
rm -rf sysError.log
rm -rf Run11TPC_xl.log
rm -rf Run14TPC_xl.log
